# Generated by Django 4.0.3 on 2022-05-11 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_customer_email_alter_orders_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='shipping_address',
        ),
        migrations.AddField(
            model_name='customer',
            name='billing_address',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 11, 16, 52, 4, 908184)),
        ),
    ]
