# Generated by Django 4.0.3 on 2022-05-11 15:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_rename_address_customer_shipping_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='shipping_address',
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 11, 20, 50, 40, 733716)),
        ),
        migrations.CreateModel(
            name='Shipping_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('address3', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=35)),
                ('state', models.CharField(max_length=35)),
                ('city', models.CharField(max_length=35)),
                ('postal_code', models.CharField(max_length=7)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Billing_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('address3', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=35)),
                ('state', models.CharField(max_length=35)),
                ('city', models.CharField(max_length=35)),
                ('postal_code', models.CharField(max_length=7)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
            ],
        ),
    ]
