# Generated by Django 4.0.3 on 2022-05-11 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_customer_billing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_address',
            name='phone',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='shipping_address',
            name='phone',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='billing_address',
            name='address1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='billing_address',
            name='address2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='billing_address',
            name='address3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='billing_address',
            name='city',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='billing_address',
            name='country',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='billing_address',
            name='first_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='billing_address',
            name='last_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='billing_address',
            name='postal_code',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='billing_address',
            name='state',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 11, 21, 5, 35, 65853)),
        ),
        migrations.AlterField(
            model_name='shipping_address',
            name='address1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shipping_address',
            name='address2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shipping_address',
            name='address3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shipping_address',
            name='city',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='shipping_address',
            name='country',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='shipping_address',
            name='first_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='shipping_address',
            name='last_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='shipping_address',
            name='postal_code',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='shipping_address',
            name='state',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
