# Generated by Django 4.0.3 on 2022-05-11 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_billing_address_phone_shipping_address_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 11, 21, 10, 15, 739513)),
        ),
    ]
