# Generated by Django 4.0.3 on 2022-05-15 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_orders_address_orders_billing_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='billing_address',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 15, 19, 11, 53, 72376)),
        ),
        migrations.DeleteModel(
            name='Billing_Address',
        ),
    ]
