# Generated by Django 4.0.3 on 2022-05-20 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_orders_payment_method_alter_orders_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='orderid',
            field=models.IntegerField(default=10100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 20, 15, 16, 47, 173821)),
        ),
    ]
