# Generated by Django 4.0.3 on 2022-05-20 10:27

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_orders_orderid_alter_orders_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='orderid',
        ),
        migrations.AddField(
            model_name='orders',
            name='order_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 20, 15, 27, 19, 333549)),
        ),
    ]
